# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



icons = ["app/assets/images/icons/icon1.png", "app/assets/images/icons/icon9.png", "app/assets/images/icons/icon7.png", "app/assets/images/icons/icon8.png", "app/assets/images/icons/icon4.png", "app/assets/images/icons/icon3.png", "app/assets/images/icons/icon6.png", "app/assets/images/icons/icon2.png", "app/assets/images/icons/icon5.png"]

meditation_names = ["Mindfulness", "Metta (Loving-Kindness)", "Zen Meditation", 'Qigong (Chi Gong)', "Mantra Meditation (OM)", "Transcendental Meditation (TM)", "Vipassana Meditation", "Chakra Meditation", "Kundalini Meditation"]

traditions = ["Buddhist, Western", "Buddhism", "Chinese Zen Buddhism", "Buddhism, Confucianism, Taoism", "Hinduism", "Hinduism", "Theravada Buddhism", "Yogic", "Yogic"]

meditation_about = ["Although Vipassana is synonymous with “Mindfulness” meditation, some people consider them to be slightly different. Many consider the practice of Mindfulness to be an adaptation of Vipassana, keeping certain aspects without a religious influence. This type of practice is also sometimes referred to as MBSR (Mindfulness-Based Stress Reduction) due to the fact that westerners are using it solely to reduce anxiety and stress.

The MBSR program was founded in 1979 at the University of Massachusetts by John Kabat-Zinn. It is supported by science as being beneficial for reducing stress, hence “stress reduction” in the name. Many consider mindfulness meditation (MBSR) to be among the most effective non-drug therapies for improving stress levels.", "This is a specific type of meditation that involves cultivating unconditional love and kindness towards other human beings. The practice of “metta” meditation is derived from Theravada Buddhism and is sometimes referred to as “compassion” meditation. There is scientific evidence in support of practicing metta for increased happiness, brain waves, and neural activity.

Metta is considered “love” without any sort of attachment and the goal is to increase “good will” towards others. If you were to practice this type of meditation, you’d start by directing feelings of unconditional love towards yourself. Once you were able to love yourself, you’d then expand those feelings and direct them towards others. This type of meditation may not be as popular as mindfulness, but has the ability to drastically improve mood when practiced correctly over the long-term.", "The name “Zen” meditation translates to “seated meditation” and originated in Chinese Zen Buddhism. Historians trace the practice back to the 6th Century Indian monk “Bodhidharma.” The practice generally involves sitting in the Lotus Position and observing the breath. To tame the mind, awareness is generally focused on counting or watching the breath. Many individuals that practice this specific type of meditation sit on a cushion, chair, or padded mat.

In the “Soto” teachings of Zen, observing the mind is the primary focus. In the Soto-subtype, there is no focus on any object and the goal is for the meditator to become aware of their thoughts without judgment. This could be compared to “mindfulness” in that the individual acts as an observer. In some cultures, intensive “group meditations” are practiced in a process called “Sesshin.”

This type of meditation also uses what are referred to as “koans” which help the Zen student gain insight from the Zen master. They are also commonly used to test the progress of a Zen meditator. Koans may be solved through sitting meditation (Zen), but are sometimes solved during walking meditation (Kinhin).", "This is a type of meditative practice that translates to “life energy cultivation.” It is considered a spiritual technique that is designed to unify the body, breath, and mind. It is deeply rooted in Chinese medicine and the goal is to cultivate and balance “qi” (chi) energy. It is a practice that is incorporated by various philosophies including: Buddhism, Confucianism, and Taoism.

Qigong is generally done while moving slowly, with coordination and specific breathing to elicit a calm state of awareness. Many people practice Qigong for recreation and/or relaxation benefit as opposed to spiritual enlightenment. It is considered a form of exercise as well as alternative medicine. It has also been practiced for thousands of years and in a variety of different ways.", "In the Hindu tradition, mantra meditation is popular and involves repeating sound, syllable, or word with the intention of focusing the mind. It is very difficult for the mind to focus on anything but the particular repeated sound, which is why it works well. The sound repeated can be anything, but some traditions assign meditators a specific syllable or word.

It should also be mentioned that certain schools of mantra meditation stress that the particular word as well as the meaning behind it are important, but that is a subjective (spiritual) debate. From a purely scientific perspective, the mantra’s purpose is to focus the attention – the particular word and/or sound that is repeated is not of major significance.

Mantra meditation is a practice that is primarily associated with Hinduism, but can also be used in Buddhism, Jainism, and Taoism. In the mainstream, it is common for people to reference mantra meditation as “om” (or “aum”) meditation. The important thing to remember is that a sound is repeated to focus the person’s attention.", "You’ve probably heard of the popularized form of mantra meditation called “Transcendental Meditation” (TM). This specific subtype of mantra meditation is associated with Maharishi Mahesh Yogi in 1955 and was introduced to pop-icons like The Beatles and The Beach Boys in the 1970s. Due to celebrity appeal and early introduction to the West, it has become one of the most popular types of meditation practiced throughout the world.

Although a very popular form of meditation, TM is not considered free. There are steep fees to be paid to get assigned a particular “mantra” as well as learn the proper technique. What distinguishes TM from other forms of mantra meditation is that it is considered “effortless.” In other words you aren’t necessarily building focus, rather you’re “effortlessly transcending.”

Neural correlates of TM demonstrate that within just 6 months of proper practice, brain waves are the exact same as an advanced TM meditator. However, the difference between a novice at TM and advanced practitioner is that the advanced TM practitioner has noticeably different non-meditative brain waves and is closer to the transcendental state while waking.", "The word Vipassana literally translates to “insight into reality” which is why many people refer to it as “insight meditation.” This meditative practice dates back to the 6th century BC and is derived from the Theravada Buddhist movement. Vipassana is recognized as being taught by Satya Narayan (S.N.) Goenka. The Vipassana meditation involves gaining “mindfulness” of breathing and is sometimes referred to in the United States as “Mindfulness.”

This meditation practice involves observation of breathing and contemplation. Many consider the goal to gain “insight” into the true nature of reality. The Sutta Pitaka describes “mindfulness” as entering the forest and sitting beneath a tree to watch the breath. If the breath is “long,” notice that it is long and if the breath is “short,” notice that it is short. By observing your breathing, perceptual changes take place in the brain, creating new insights.

Vipassana has emerged as among the most popular styles of meditation in the United States. It helps increase internal awareness and has been scientifically proven to reduce stress. If you’ve never meditated before, this may be an ideal practice to start with.", "Many people practice yogic forms of meditation as a way to achieve mental freedom, self-knowledge, and self-realization (moksha). Yoga is considered an integrated form of physical, mental, and spiritual practices and is used in Hinduism, Buddhism, and Jainism. Yoga dates back to pre-Vedic Indian tradition, but is hypothesized to have emerged between the 6th century B.C. and the 5th century B.C.

Practicing yoga typically consists of the following: conduct (yamas and niyamas), postures (asanas), breathing techniques (pranayama), and meditation. The last four limbs of yoga include: pratyahara, dharana, dhyana, and samadhi. It is these four limbs that embody the meditative practice in yoga. The specific type of meditation that you use to enhance yoga practice depends on what you’re comfortable with and/or what you’d like to experience.", "Many people practice yogic forms of meditation as a way to achieve mental freedom, self-knowledge, and self-realization (moksha). Yoga is considered an integrated form of physical, mental, and spiritual practices and is used in Hinduism, Buddhism, and Jainism. Yoga dates back to pre-Vedic Indian tradition, but is hypothesized to have emerged between the 6th century B.C. and the 5th century B.C.

Practicing yoga typically consists of the following: conduct (yamas and niyamas), postures (asanas), breathing techniques (pranayama), and meditation. The last four limbs of yoga include: pratyahara, dharana, dhyana, and samadhi. It is these four limbs that embody the meditative practice in yoga. The specific type of meditation that you use to enhance yoga practice depends on what you’re comfortable with and/or what you’d like to experience."]


meditation_instructions = ["To practice mindfulness meditation, you simply focus on the present moment or life circumstance and pay attention to all emotions, physical sensations, and thoughts that you experience, without judgment. The efficacy of mindfulness stems from non-judgment and non-attachment. Like many forms of meditation, you sit comfortably, close your eyes, and focus on your breathing.

As you focus on breathing, you become distracted with sensations, thoughts, etc. Whenever you get distracted, you simply redirect your focus back to the breathing without getting frustrated. The more you practice this, the easier it will be to cope with stressors because you’re training your brain to avoid attachment and judgment to sensations and/or thoughts.

You don’t even necessarily need to sit with eyes closed to be “mindful.” You can practice mindfulness while you’re in a traffic jam, walking, out at the park, brushing your teeth, or eating. The practice simply helps you become increasingly aware and non-reactive to your consciousness. If you don’t want any sort of religious dogma attached to your meditative practice, this is the one to try.", "To perform Metta meditation, you sit down in a comfortable position with eyes closed. You then use your mind (and heart) to create feelings of unconditional kindness and good-will towards yourself. It may take awhile to send and accept the feelings of kindness within yourself, but eventually you’ll get the hang of it.

After you’ve become adept at directing loving-kindness feelings toward yourself, you then pick a good friend (or family member) to direct these feelings towards. Once you’ve mastered directing these feelings toward a loved-one, you then pick a “neutral” person (possibly a stranger or acquaintance) to direct these feelings towards. As you continue, you will eventually direct feelings of loving-kindness towards a difficult person (or someone you dislike).

Eventually you’ll send simultaneous feelings of loving-kindness towards everyone including: yourself, a close friend, the neutral person, and the difficult person. Once you’ve figured that out, you then can send these feelings of loving-kindness towards the entire “universe.” The ultimate goal is to wish genuine “good-will,” peace, and happiness towards all beings.

When consistently practiced, feelings of pure “joy” will arise. Those who suffer from depression, negative thinking, and anger outbursts will significantly benefit from this type of meditation if practiced correctly. It is impossible to feel authentic loving-kindness (compassion) and anger at the same time. The more you practice this type, the more your “happiness” center within the brain is stimulated.", " To practice Zen meditation, you’ll want to either find a mat, cushion, or sit on a chair in a cross-legged position. Although historically the practice involved sitting in a lotus or half-lotus, you can modify for comfort. Be sure to use good posture, keep the mouth closed and eyes lowered. Some sources suggest your gaze should be directed 3 feet in front of you on the ground.

Focus: To cultivate your focus, you can direct attention on your breath; flowing in and out through your nose. If necessary, you can count each breath to a count of 10 and then repeat. Counting helps some people focus. Each time your attention drifts, simply bring your attention back to the breath.
Observation: With this type of meditation, you don’t focus on anything, rather you focus on staying in the present moment, and simply observing your stream-of-consciousness thinking. You are aware of the thoughts flowing naturally through your head, but you aren’t judging them or reacting to them – just observing.
Kinhin (Walking): This is a type of meditation that involves walking, and is practiced between periods of the sitting (zazen) meditation. This type involves walking in a clockwise pattern around a room. Generally one hand is in a “fist” (or closed) while the opposite hand is covering the fist. During the walking meditation, one step is taken after each full breath. The speed of this form of meditation can be extremely slow or quicker (rivaling a slow-jog).", "Assuming you want to learn Qigong, your best bet is to learn from an advanced instructor or watch a tutorial DVD. When starting out, you should learn the basics and strive to keep things as simple as possible. Once you master the basics, then you can move on to some intermediate or advanced practices.

When starting out you may focus on some simple movements and breathing patterns with awareness and/or visualization. Chanting or the usage of sound is also common in this type of practice. You’ll want to work with an instructor to get a better understanding of “softness” of gaze, stance solidity, relaxation, and general balancing.

If you’re in the more advanced stages of Qigong, you may focus on incorporating equanimity, tranquility, and stillness. Those that are highly advanced in Qigong generally are able to perform the practice with minimal motion. Before starting Qigong, do some research and identify the type you’d like to practice – some are more related to martial arts, while others are more geared towards those seeking spiritual development.

If we’re specifically talking about the meditation, you could practice Qigong in a seated format. Get comfortable and balance your body, maintaining a sense of centeredness. Next focus on relaxing your entire body as deeply as possible. Followed by physical and internal relaxation of the body, you then focus on your breathing to enhance its depth, length, and softness.

Your mind should become calm once you’ve softened your breathing. After this, you can direct focus towards the “lower dantien” which has been described as your body’s “root.” Think of it as your center of gravity. As you focus on the lower dantien (located three finger widths below the navel and two finger widths behind the navel), you build up more “qi” (energy).

By focusing on this exact spot, you are building up more “energy” for your body. Simply feel the energy circulating throughout your body as it builds up and maintain focus on the lower dantien.", "Assuming you want to practice “mantra” meditation, you first need to come up with a mantra. Generally these mantras are assigned by an advanced meditative teacher or a specific sound is chosen for a spiritual purpose. That said, you can choose whatever sound, word, or syllable you’d like to use and stick with it. The word that you select isn’t all that important.

Sit in a comfortable position with good posture and close your eyes. Next, you may want to repeat your mantra softly aloud to let it sink in. Then stop speaking your mantra and repeat it silently (over and over) in your mind for a specific period of time or number of reps. When you’re just starting out, you may notice that your focus may drift to other thoughts, emotions, or discomfort.

Simply notice these sensations and bring your focus back to repeating the mantra. The idea is that the mantra will enhance both relaxation and focus. It is also a way to become aware of deeper states of consciousness or awareness between “thoughts.” Mantra meditation is preferred by some over breath-focused attention because it’s relatively easy to focus on a repeated sound.", "To perform transcendental meditation, you get assigned a “mantra” that fits you individually based on when you were born and your sex. Your “guru” will then explain how you should repeat this mantra as well as for how long you should practice. I can’t get into too many details simply because TM is licensed technique that is not freely available.

Many people end up practicing TM for periods of 10 to 20 minutes either once or twice per day with eyes closed. Although it can be costly to get proper TM instruction, many people appreciate the technique more after they’ve had to fork over some cash and also put more effort into it. Other types of meditation may be “free” but may not be as motivating to continue because the person never had to pay to properly learn the technique.

The cost is near $1000 to learn from a TM teacher in the United States, and a spin-off called “Natural Stress Relief” has also emerged as an alternative in 2003 for just under $50. If you scour the internet, you can find how TM is done for free. There is science supporting TM for increasing alpha waves in the prefrontal cortex, meaning it will make you relax and potentially improve creativity and/or focus. It’s not much different than “mantra” meditation that can be learned for free (although it claims to be).", "There is no “perfect” way to practice Vipassana meditation, but certain forms claims to be more authentic than others. Most practitioners of Vipassana suggest that a newbie starts with “mindfulness of breathing.” Once the person becomes adept at observing the breathing without judgment, they then may move on to develop “insight” associated with bodily sensations and other mental patterns.

To practice Vipassana meditation, sit in a comfortable position (wherever you want) and maintain good posture. Focus your attention on the in-flow and out-flow of your breath. You can focus on a specific area of the body (e.g. nostrils or belly) that are involved in the breathing process if it helps. During the breathing, sensations and thoughts will arise. Your goal isn’t to become frustrated with these thoughts and sensations, rather it is to calmly refocus your attention on the breath.", "This type of meditation is based on the 7 main energy centers throughout the body called “chakras.” To perform chakra meditation, you would specifically focus on one of these centers (e.g. the heart chakra) and use a specific mantra (e.g. “yam”) to open up or expand energy flow in this area. Each chakra has a specific mantra correlate.

Crown = Mmm
Third-eye = Ooo
Throat = Ham
Heart = Yam
Solar Plexus = Ram
Sacral = Vam
Root = Lam", "Originally known as “laya yoga,” kundalini translates to “serpent” or snake. This form of meditation is practiced with the intention of unleashing “kundalini energy” that lies dormant at the base of the spine. Those practicing Kundalini Meditation generally experience drastic changes in the functioning of their body, nervous system, and physiology as the “kundalini” energy rises from the spine.

This energy rises from “lower” energy centers to “higher” energy centers in the body. It typically involves a specific breathing technique that involves “alternate nostril” inhalation. In other words, you’d close your right nostril on the first inhale, and your left nostril on the second. The thought behind the technique is to “cleanse” certain energy channels to help awaken the Kundalini or “serpent” energy."]


counter = 0

9.times do
  Meditation.create(
  name: meditation_names[counter],
  icon: File.open(File.join(Rails.root, icons[counter])),
  instructions: meditation_instructions[counter],
  about: meditation_about[counter],
  tradition: traditions[counter]
  )
  counter += 1
end
